### ISSUE TITLE
system.tl.*.proto file header mistake code annotation

### ISSUE THREAD

**Issue by ckzhangss** [teamgram/proto#2]
In the  system.tl.*.proto file header  code annotation

```
 * WARNING! All changes made in this file will be lost!
 * Created from 'scheme.tl' by 'mtprotoc'
```

It's a mistake?   *.proto is source definition file.

![image](https://github.com/user-attachments/assets/289d5624-694f-43a6-911f-b966b4a9a022)

**Comment by wubenqi** [comment]
This is not a mistake.

**Comment by ckzhangss** [comment]
> This is not a mistake.
copy that
